export const IS_LOADING = 'IS_LOADING';

export const GET_STAR_WAR_LIST_BEGIN = 'GET_STAR_WAR_LIST_BEGIN';
export const GET_STAR_WAR_LIST_SUCCESS = 'GET_STAR_WAR_LIST_SUCCESS';
export const GET_STAR_WAR_LIST_FAILED = 'GET_STAR_WAR_LIST_FAILED';

export const GET_STAR_WAR_INFO_BEGIN = 'GET_STAR_WAR_INFO_BEGIN';
export const GET_STAR_WAR_INFO_SUCCESS = 'GET_STAR_WAR_INFO_SUCCESS';
export const GET_STAR_WAR_INFO_FAILED = 'GET_STAR_WAR_INFO_FAILED';

export const GET_FILMS_INFO_BEGIN = 'GET_FILMS_INFO_BEGIN';
export const GET_FILMS_INFO_SUCCESS = 'GET_FILMS_INFO_SUCCESS';
export const GET_FILMS_INFO_FAILED = 'GET_FILMS_INFO_FAILED';